# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: hub.icc-tech.ru/file/php

# Select what we should cache between builds
cache:
  paths:
  - vendor/

before_script:
- composer install

test:
  script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never